### ISSUE TITLE
Code

### ISSUE THREAD

**Issue by Robinlovelace** [fiftysevendegreesofrad/TrafRed#1]
It would be great if the code, which is open in Google, could be checked into this repo: https://colab.research.google.com/drive/1UNXNDHjF3ZiRkm0KEDSyuC_LlI4SkGcy?usp=sharing

**Comment by Robinlovelace** [comment]
Great to see the code, thanks Crispin! https://github.com/fiftysevendegreesofrad/TrafRed/blob/master/TrafRed.ipynb

**Comment by fiftysevendegreesofrad** [comment]
Recommend viewing the code in colab though. Github displays it wrong, very
wrong (like syntactically incorrect python)!
